version: '2'

services:
  ns3:
    build:
      context: ./files
    image: ns3
    container_name: ns3
    volumes:
      - ./scratch:/workspace/source/ns-3.28/scratch
      - ./outputs:/workspace/source/ns-3.28/outputs
    command: miniproj_simu
